apiVersion: v1
kind: Service
metadata:
  labels:
    component: front
  name: frontend-svc
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: frontend
  selector:
    app: todo
    component: front
  type: LoadBalancer
