apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: deployement
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 10m
        args:
        - redis-server 
        - --requirepass ccp2 
        - --appendonly yes
